config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :movies do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
  end

  root 'movies#index'
end

app/models/movie.rb
class Movie < ActiveRecord::Base

  searchkick
  belongs_to :user
  has_many :reviews

  has_attached_file :image, styles: {medium: '300x300', thumb: '100x100'}, default_url: "images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :user
  belongs_to :movie
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :movies
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show ]

  def search
    if params[:search].present?
      @movies = Movie.search params[:search]
    else
      @movies = Movie.all
    end
  end

  def index
    @movies = Movie.all
  end

  def show
    @reviews = Review.where(movie_id: @movie.id).order("created_at DESC")
    if @reviews.blank?
      @avg_review = 0
    else
      @avg_review = @reviews.average(:rating).round(2)
    end
  end

  def new
    @movie = current_user.movies.build
  end

  def edit
  end

  def create
    @movie = current_user.movies.build(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_movie
      @movie = Movie.find(params[:id])
    end

    def movie_params
      params.require(:movie).permit(:title, :description, :movie_length, :director, :rating, :image)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_movie
  before_action :authenticate_user!

  respond_to :html

  def new
    @review = Review.new
  end

  def edit
  end

  def create
    @review = Review.new review_params
    @review.user_id = current_user.id
    @review.movie_id = @movie.id
    if @review.save
      redirect_to @movie
    else
      render :new
    end
  end

  def update
    @review.update(review_params)
  end

  def destroy
    @review.destroy
    redirect_to root_path
  end

  private
    def set_review
      @review = Review.find(params[:id])
    end

    def set_movie
      @movie = Movie.find params[:movie_id]
    end
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MovieReview
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'shared/header'
    .container
      = render 'shared/messages'
      = yield

app/views/movies/_form.html.haml
= form_for @movie, html: { multipart: true } do |f|
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :description
    %br/
    = f.text_area :description
  .field
    = f.label :movie_length
    %br/
    = f.text_field :movie_length
  .field
    = f.label :director
    %br/
    = f.text_field :director
  .field
    = f.label :rating
    %br/
    = f.text_field :rating
  .field
    = f.label :image
    %br/
    = f.file_field :image
  .actions
    = f.submit

app/views/movies/edit.html.haml
%h1 Editing movie
= render 'form'
= link_to 'Show', @movie
|
= link_to 'Back', movies_path

app/views/movies/index.html.haml
- unless user_signed_in?
  .jumbotron
    %h1 Your favorite Movies Reviewed
    %p Tote bag meditation ennui distillery ugh vice, selvage migas. Semiotics schlitz poutine neutra selvage, forage normcore squid sriracha master cleanse fap photo booth.
    %p= link_to "Sign up to write a review", new_user_registration_path, class: 'btn btn-primary btn-lg'
.row
  - @movies.each do |movie|
    .col-sm-6.col-md-3
      .thumbnail
        = link_to (image_tag movie.image.url, class: 'image'), movie

app/views/movies/new.html.haml
%h1 New movie
= render 'form'
= link_to 'Back', movies_path

app/views/movies/search.haml
.row
  - @movies.each do |movie|
    .col-sm-6.col-md-3
      .thumbnail
        = link_to (image_tag movie.image.url, class: 'image'), movie

app/views/movies/show.html.haml
.panel.panel-default
  .panel-body
    .row
      .col-md-4
        = image_tag @movie.image.url(:medium)
        .star-rating{"data-score" => "#{@avg_review}"}
        %em= "#{@reviews.length} reviews"
        .table-responsive
          %table.table
            %tbody
              %tr
                %td
                  %strong Title:
                %td= @movie.title
              %tr
                %td
                  %strong Description:
                %td= @movie.description
              %tr
                %td
                  %strong Length:
                %td= @movie.movie_length
              %tr
                %td
                  %strong Director:
                %td= @movie.director
              %tr
                %td
                  %strong Rating:
                %td= @movie.rating
        = link_to "Write a Review", new_movie_review_path(@movie)
      .col-md-7.col-md-offset-1
        %h1.review-title= @movie.title
        %p= @movie.description

        - if @reviews.blank?
          %h3 No reviews just yet, would like to add the first!
          = link_to "Add Review", new_movie_review_path(@movie), class: 'btn btn-danger'
        - else
          - @reviews.each do |review|
            .reviews
              .star-rating{"data-score" => "#{review.rating}"}
              %p= review.comment

= link_to 'Edit', edit_movie_path(@movie)
= link_to 'Back', movies_path

%script
  $('.star-rating').raty({
  path: '/assets/',
  readOnly: true,
  score: function() {
  return $(this).attr('data-score');
  }
  });

app/views/reviews/_form.html.haml
= simple_form_for([@movie, @review]) do |f|
  = f.error_notification
  .field
    #star-rating
  .form-inputs
    = f.input :comment
  .form-actions
    = f.button :submit

%script
  $('#star-rating').raty({
  path: '/assets/',
  scoreName: 'review[rating]'
  });

app/views/reviews/edit.html.haml
%h1 Editing review
= render 'form'
= link_to 'Back', movie_path(@movie)

app/views/reviews/new.html.haml
%h1 New review
= render 'form'
= link_to 'Back', movie_path(@movie)

app/views/shared/_header.haml
%nav.navbar.navbar-default
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Brand", root_path, class: 'navbar-brand'
    / Collect the nav links, forms, and other content for toggling

    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        - if user_signed_in?
          %li
            = link_to new_movie_path, class: "active" do
              %span.sr-only (current)
              New Movie
          %li
            = link_to edit_user_registration_path do
              Account
        - else
          %li
            = link_to "Sign Up", new_user_registration_path, class: "active"
          %li
            = link_to "Log in", new_user_session_path, class: "active"
      = form_tag search_movies_path, method: :get, class: 'navbar-form navbar-right', role: 'search' do
        .form-group
          = text_field_tag :search, params[:search], class: 'form-control'
          = submit_tag "Search", name: nil, class: 'btn btn-default'

app/views/shared/_messages.haml
- flash.each do |name, msg|
  %div.alert.alert-dismissable.notifications{ class: "alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
    %button.close{ data: { dismiss: "alert"}, aria: { hidden: true}, type: "button" } &times;
    = msg